### PR TITLE
fix: make the version number correct

### LINKED ISSUE #127: Steiger gives you "unknown" when you ask for its version
Screenshot 2024-11-16 at 14 56 01

### PR DESCRIPTION
**Pull request by illright**
Closes #127. I wanted to go fancy with colors in the output but realized that it doesn't actually improve much. So went with as much of a default presentation as possible :)

image

### CODE REVIEW

File: packages/steiger/src/cli.ts [hunk 1]
```diff
@@ -55,28 +72,22 @@ const yargsProgram = yargs(hideBin(process.argv))
   })
   .help('help', 'display help message')
   .alias('help', 'h')
-  .version()
+  .version(
+    [
+      packageJson.version,
+      $plugins
```
Comment (daniilsapa) [inline packages/steiger/src/cli.ts:78]: We used to define and export getter functions from the config module before (like `getEnabledRules`, and `getGlobalIgnores`). Does it make sense in the case of plugins too for consistency?

**Comment by daniilsapa** [comment]
@illright 
Looks great. I don't have any suggestions except for a single tiny one that I left a comment for. Thank you

File: packages/steiger/src/cli.ts (hunk 1 above)
Comment (daniilsapa) [reply packages/steiger/src/cli.ts:78]: ...so it just helps us to keep the codebase less dependent on the store solution and keep the code that interacts with effector mainly inside `models/config`

Comment (illright) [reply packages/steiger/src/cli.ts:78]: I don't like getters for the sake of getters. In this case, it doesn't matter architecturally if we do `$plugins.getState()` or `getPlugins()`, because we aren't using Effector-specific functionality either way.

As for consistency, that is not the only store that's exported there, so we didn't have consistency there to begin with :)
